// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1622902451);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1622902421);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 109);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"95188\":1622902438713,\"95353\":1622902438712,\"95357\":1622902438710}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6746b1d1-c4c8-4561-8951-64409ccdf63c}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1622902424);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1622902429618");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1622924029618");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.checkDefaultBrowser", true);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1622902424");
user_pref("browser.startup.homepage_override.buildID", "20210531160138");
user_pref("browser.startup.homepage_override.mstone", "89.0");
user_pref("browser.startup.lastColdStartupCheck", 1622902423);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1622902425646");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "89.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "81bf927fb2564bac8675ae7399e30c23");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210531160138");
user_pref("extensions.lastAppVersion", "89.0");
user_pref("extensions.lastPlatformVersion", "89.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"8f5b0ec8-7c9d-43e3-985c-daa00b2be7e7\",\"formautofill@mozilla.org\":\"721f39cc-3c4c-446d-8684-d3d8de65806a\",\"pictureinpicture@mozilla.org\":\"3d662a6f-e586-4020-9624-858248e7175c\",\"screenshots@mozilla.org\":\"ec0da98d-2690-4dfa-9ab1-38277246b7d0\",\"webcompat-reporter@mozilla.org\":\"e659ce6b-eedf-4469-a6d6-6bd83d258911\",\"webcompat@mozilla.org\":\"2e844775-a448-4e1e-93e2-1bcbb21b7dfc\",\"default-theme@mozilla.org\":\"ace2f694-d041-4fb9-b03e-f169e9db68cf\",\"google@search.mozilla.org\":\"c84adb63-4444-42cd-afd0-5b399153c705\",\"amazondotcom@search.mozilla.org\":\"b6570338-f113-4e07-ad34-349723a246c1\",\"wikipedia@search.mozilla.org\":\"70348806-73ce-4004-995d-0f958deecfc7\",\"bing@search.mozilla.org\":\"27c3b64d-a975-4d94-9f56-ff9dcb0f853e\",\"ddg@search.mozilla.org\":\"05270dbe-417a-4ae4-8231-891092688aa5\",\"firefox-compact-dark@mozilla.org\":\"7afac416-2848-4717-97aa-a54d4f65aace\",\"addon@darkreader.org\":\"78fecd2e-202c-49bd-932c-19c4d0b6112d\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1622902425);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "41709fc0-a1b0-48a0-9d5a-a8a5b9cba8f6");
user_pref("toolkit.startup.last_success", 1622902420);
user_pref("toolkit.telemetry.cachedClientID", "684c390b-6cfb-40fc-806d-8e55b95fad98");
user_pref("toolkit.telemetry.previousBuildID", "20210531160138");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
