// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "3e7786e2-8808-4be5-97dc-2143fea384bd");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1621759022);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1621759011);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1621759006);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1621759052);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1621758992);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.discoverystream.rec.impressions", "{\"93653\":1621759035698,\"93966\":1621759035697,\"94076\":1621759035694}");
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e0a84fff-67b4-4971-8743-22ca8f4dbaf2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1621759002);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1621759027123");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1621760832123");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1621759012695");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1621780612695");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1621759000");
user_pref("browser.startup.homepage_override.buildID", "20210506154205");
user_pref("browser.startup.homepage_override.mstone", "88.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1621758998);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1621759008616");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "d4d28cc00ca847a3bd14ee77b5c23703");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210506154205");
user_pref("extensions.lastAppVersion", "88.0.1");
user_pref("extensions.lastPlatformVersion", "88.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"dcd2c895-df57-4d1f-99b2-205f76d677ee\",\"formautofill@mozilla.org\":\"8ff44879-39d7-488a-93f8-aed409ab152a\",\"pictureinpicture@mozilla.org\":\"4aea1f82-ad22-43a1-8654-8fc78fd47b6c\",\"screenshots@mozilla.org\":\"0ec1e285-2b6d-4b1a-b86b-68d27815c2a4\",\"webcompat-reporter@mozilla.org\":\"426a5bc6-c1e7-421b-8168-bf70967689aa\",\"webcompat@mozilla.org\":\"e64e8793-6f12-473e-bf14-dd0765e159fd\",\"default-theme@mozilla.org\":\"a1fce17f-9f69-4c15-af78-b48537cec413\",\"google@search.mozilla.org\":\"443d935a-5efd-484e-bfdf-8c16dcba9865\",\"amazondotcom@search.mozilla.org\":\"652085ca-04b0-457a-955b-9752f3f93ab7\",\"wikipedia@search.mozilla.org\":\"7583a63d-ff58-41e5-825d-14854e163f37\",\"bing@search.mozilla.org\":\"d419530e-1477-42bf-8bd0-7c28ef502740\",\"ddg@search.mozilla.org\":\"245f83fb-0d9e-4e52-819e-e7a83dcce685\",\"addon@darkreader.org\":\"064bf30f-7806-4485-a33c-3092624a23e8\",\"firefox-compact-dark@mozilla.org\":\"bc31af3f-c890-447d-98f8-8756bad977ab\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1621759008);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "714def30-5bec-4095-b06e-960d85c963fa");
user_pref("security.sandbox.plugin.tempDirSuffix", "2c15b578-298f-455a-9bec-724adef8d046");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1621758988);
user_pref("toolkit.telemetry.cachedClientID", "554e97ae-4565-42b3-b2b0-93061a7a44c8");
user_pref("toolkit.telemetry.previousBuildID", "20210506154205");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
