// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "62be883d-b936-4ba0-b879-6754fb190cbd");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1621561580);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1621561750);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1621561747);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1621561700);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1621561610);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1621561549);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 107);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories", false);
user_pref("browser.newtabpage.activity-stream.feeds.snippets", false);
user_pref("browser.newtabpage.activity-stream.feeds.topsites", false);
user_pref("browser.newtabpage.activity-stream.impressionId", "{d1f29028-5bbe-492a-863d-08fa388b7d83}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.region.update.updated", 1621561555);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1621561604377");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1621563392377");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1621561561769");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1621583161769");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210506154205");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1621561746");
user_pref("browser.startup.homepage_override.buildID", "20210506154205");
user_pref("browser.startup.homepage_override.mstone", "88.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1621561744);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"addon_darkreader_org-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"addon_darkreader_org-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1621561556956");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "88.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "541d75ee7f9b43c8a9490d5a35add730");
user_pref("extensions.activeThemeID", "firefox-compact-dark@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210506154205");
user_pref("extensions.lastAppVersion", "88.0.1");
user_pref("extensions.lastPlatformVersion", "88.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/theme");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"d18f5cc7-caad-4094-8991-a6ae92055ef6\",\"formautofill@mozilla.org\":\"6459279b-bdc4-4032-bc58-5a58e14aac51\",\"pictureinpicture@mozilla.org\":\"07a875a9-7039-4cc3-b05f-28a93a79b731\",\"screenshots@mozilla.org\":\"87da5755-8285-43db-8c18-237395275b37\",\"webcompat-reporter@mozilla.org\":\"e5af950b-ca6d-4cfc-bfca-9f9970a2b579\",\"webcompat@mozilla.org\":\"d2c7bb40-1d0e-403c-9381-0ee41d63e7f9\",\"default-theme@mozilla.org\":\"6ab1cf61-0646-47ff-afd9-b55e2cc87a5a\",\"google@search.mozilla.org\":\"cd4306f2-2a45-4603-a1a0-95a0f1a20377\",\"amazondotcom@search.mozilla.org\":\"e2ec2563-ac53-4427-81b6-be8341baeba9\",\"wikipedia@search.mozilla.org\":\"9dc73acb-9217-4942-9509-d54a9f397b05\",\"bing@search.mozilla.org\":\"e94d2d6e-c3d5-4559-bdd8-82838a5db55f\",\"ddg@search.mozilla.org\":\"947a4c81-5a10-457a-bb36-909906dab07e\",\"firefox-compact-dark@mozilla.org\":\"2a7260a4-e959-460a-9cb3-fa003085b3e3\",\"addon@darkreader.org\":\"b3a11de4-7967-40ee-bd42-4ce0a50ff97f\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1621561556);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "6ffd20de-79a5-4a52-bded-2d90d2d1e20c");
user_pref("security.sandbox.plugin.tempDirSuffix", "386308fb-3b48-43b5-895b-4e2907cc20ce");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1621561743);
user_pref("toolkit.telemetry.cachedClientID", "cf770a7e-c81d-44ce-a77c-a817db156e6a");
user_pref("toolkit.telemetry.previousBuildID", "20210506154205");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
